monitor.alsa.rules = [
  {
    matches = [{ device.name = "alsa_card.usb-Divoom_Ditoo_usb_audio_20190808-00" }]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
]
